
# Transformed Infra
```yml
name: Terraform GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.2.0"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve \
          -input=false \
          -lock=false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
```
# Refactoring Suggestions
# Consider splitting resources into modules
# Use variables for AMI and instance type
# Follow naming conventions for Jenkins resources

// -- Jenkins Pipeline Optimization Suggestions --
// - Automate Jenkins pipeline with stages like Build, Test, Deploy. Ensure proper error handling and post-build actions.
// - Use workspaces for dev/staging/prod. Automate with GitHub Actions using init, validate, plan, and apply steps. Store state securely using S3 and DynamoDB.

// -- Monitoring Suggestions --
// Add deployment monitoring hooks to track release success and error rates.

# CI/CD Tip: Automate your deployment process with stages like Build, Test, and Deploy. Use proper error handling and post-build actions to ensure stability.

# Terraform Tip: Use separate workspaces for dev/staging/prod environments. Automate Terraform with GitHub Actions using init, validate, plan, and apply stages. Store the Terraform state securely (e.g., S3 + DynamoDB for locking).