
# Transformed Infra
```yml
name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Test
        run: |
          ./gradlew build
          ./gradlew test

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Cache Gradle
        uses: actions/cache@v2
        id: cache
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
```
# Refactoring Suggestions
# Follow naming conventions for Jenkins resources

// -- Jenkins Pipeline Optimization Suggestions --
// - Include a 'post' section for better visibility into pipeline success or failure.
// - Use parameters to make the pipeline reusable for different environments or builds.

# CI/CD Tip: Automate your deployment process with stages like Build, Test, and Deploy. Use proper error handling and post-build actions to ensure stability.